config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections
  has_many :enrollments
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end
	
	def premium?
		! free?
	end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
	has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :courses
	has_many :enrollments
	has_many :enrolled_courses, through: :enrollments, source: :course
  
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

	def enrolled_in?(course)
		return enrolled_courses.include?(course)
	end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson


  def show
  end


  private

  def require_authorized_for_current_lesson
    unless current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert:'Not Authorized...Please enroll first'
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	
	def destroy
	end
	
	def edit
	end
	
	def update
	end
	
	def create
	end
	
	def new
	end
	
	def show
	end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

	def terms_of_service

	end

  def privacy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollment_helper.rb
module EnrollmentHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="hero">
	<div class="hero_back">
	<br />
		<div class="frosty col-10 offset-1">
		<br />
		<h1>Learn Magic from the Pros</h1>
		<br />
		<h2>I'm an illusionist, Michael</h2>
		<br />
		<%= link_to 'Learn More', courses_path, class: 'btn btn-succes' %>
		<br />
		<br/>
			<div class="row feature text-center">
				<div class="col-12 col-sm">
					<h3>Amazing Courses</h3>
					<br />
					<p>Choose from any number of courses to study with amazing teachers.</p>
				</div>
				<div class="col-12 col-sm">
					<h3>Learn At Your Own Pace</h3>
					<br />
					<p>Enroll and access a courses archive of lessons.</p>
				</div>
				<div class="col-12 col-sm">
					<h3>Join our Community</h3>
					<br />
					<p>Learn with a community of like-minded individuals.</p>
				</div>
			</div>
		<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nibh non varius hendrerit. Phasellus a condimentum nibh. Integer convallis massa non libero posuere, et euismod nibh hendrerit. Integer dapibus congue libero, eu aliquam purus tristique eget. Ut metus neque, varius a dignissim sed, ultricies in odio. Suspendisse potenti. Cras ullamcorper, justo at fringilla rutrum, urna sapien vestibulum lacus, ut fringilla tortor nunc sed felis. Sed et risus ut metus volutpat vestibulum. Cras laoreet ex quis dolor facilisis hendrerit.
		</p>

		<p>
		Etiam a lectus sit amet purus lacinia ornare vel sed massa. In dictum fringilla turpis, at convallis felis tincidunt vel. Nam vestibulum ullamcorper elit id tempus. Duis facilisis facilisis nisi. Maecenas bibendum orci eu semper bibendum. Pellentesque iaculis eros non nisl viverra luctus. Aenean est augue, convallis quis tellus non, viverra ultricies nisl.
		</p>
		</div>
	</div>
</div>

app/views/static_pages/privacy.html.erb
<br />

<div class="frosty col-10 offset-1">
  <h1>Privacy Policy</h1>

  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin nibh non varius hendrerit. Phasellus a condimentum nibh. Integer convallis massa non libero posuere, et euismod nibh hendrerit. Integer dapibus congue libero, eu aliquam purus tristique eget. Ut metus neque, varius a dignissim sed, ultricies in odio. Suspendisse potenti. Cras ullamcorper, justo at fringilla rutrum, urna sapien vestibulum lacus, ut fringilla tortor nunc sed felis. Sed et risus ut metus volutpat vestibulum. Cras laoreet ex quis dolor facilisis hendrerit.
  </p>
</div>