config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections
  has_many :enrollments
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end
	
	def premium?
		! free?
	end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
	has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :courses
	has_many :enrollments
	has_many :enrolled_courses, through: :enrollments, source: :course
  
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

	def enrolled_in?(course)
		return enrolled_courses.include?(course)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_course, only: [:show]


  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

	def show
		@section = Section.new
		@lesson = Lesson.new
	end


  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end


  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :image, :description, :tags, :cost)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson


  def show
  end


  private

  def require_authorized_for_current_lesson
    unless current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert:'Not Authorized...Please enroll first'
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	
	def destroy
	end
	
	def edit
	end
	
	def update
	end
	
	def create
	end
	
	def new
	end
	
	def show
	end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollment_helper.rb
module EnrollmentHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<div class="hero">
	<br />
	<div class="navbar-brand col-10 offset-1">

		<div class="frosty col-10 offset-1">
		<h1 class="text-truncate">Learn something today</h1>
		</div>

		<br />
		<br />
		<% @courses.each do |course| %>
		<div class="frosty col-10 offset-1">

		<h3 class="text-truncate">
		<%= link_to course.title, course_path(course) %>
		</h3>

		<h6 class="course_description">
		<%= course.description %>
		</h6>

		<br />
		<%= image_tag course.image, class:'img-fluid' %>
		<br />
		<br />
		<%= link_to 'More details...', course_path(course), class: 'btn btn-primary btn-large' %>
		<br />
		<br />
		<br class="clr" />
		</div>
		<hr>
		<% end %>
	  <br class="clr" />
	</div>
</div>

app/views/courses/show.html.erb
<div class="frosty col-10 offset-1">
<h1><%= @course.title %></h1>
  <%= image_tag course.image, class: 'img-fluid' %>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>

      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %>

		<br />
		<br />
			<% if current_user %>
				<% if current_user.enrolled_in?(@course) %>
					<h3 class="badge badge-info">You are enrolled</h3>
				<% else %>
					<%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
					<% if @course.free? %>
						<%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
					<% else %>
					<%= form_tag course_enrollments_path(@course) do %>
						<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
										data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
										data-email="<%= current_user.email %>"
										data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
										data-amount="<%= (@course.cost * 100).to_i %>"
										data-locale="auto"></script>
						<% end %>
					<% end %>
				<% end %>
			<% else %>
				<h3 class="badge badge-info">Sign in to enroll</h3>
			<% end %>
    </div>

    <div class="col-sm-8 col-12">
      <%= @course.description %>
    </div>
  </div>

  <div class="col-12">
    <% @course.sections.each do |section| %>
      <br /><br />
      <div class="section">
        <h4>
          <%= section.title %>
        </h4>
        <div class="row">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <div class="col-12 col-sm-6">
              <div class="lesson text-center">
                <br />
                <%= link_to lesson_path(lesson) do %>
                  <b><%= lesson.title %></b>
                  <br />
                  <%= lesson.subtitle %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <br class="clr" />
      </div>
    <% end %>
  </div>
</div>